tmuxSHELLS="$HOME/.config/tmux/tmux-initial.conf"
if [[ -z "$DISPLAY" ]]; then
  case "$(tty)" in
    /dev/tty1)
      if ! tmux has -t xorg; then
        tmux start \; \
          new-session -d -s xorg "PATH=/usr/bin:$PATH startx"
        if ! tmux has -t shell; then 
          tmux source "$tmuxSHELLS"
        fi
        logout
      elif tmux has -t shell; then
        exec tmux a -t shell         
      else:
        tmux start \; \
          source "$tmuxSHELLS"
        exec tmux a -t shell
      fi
      ;;
    /dev/tty[2-4]) 
      if tmux has; then
        exec tmux a
      else:
        tmux start \; \
          source "$tmuxSHELLS"
        exec tmux a -t shell
      fi
      ;;
  esac
fi

