if [[ -z $DISPLAY ]]; then
  case $(tty) in
    /dev/tty1)
      exec tmux new-session -d -s X11 startx
      ;;
    # *) 
      #  exec fbpad
      # ;;
  esac
  # if [[ $(tty) = /dev/tty1 ]]; then
    # exec startx                
  # elif [[ $(tty) != /dev/tty1 ]]; then
  #   while true; do
  #     fbpad >/dev/null 2>&1
  #   done
  # fi
fi

