#!/usr/bin/env zsh
eval $(ssh-agent -s)
ssh-add
eval $(dircolors -b ~/.config/dircolors/dircolors)
mpd
stty -ixon

if [[ -o interactive ]]; then
  mypath="$HOME/bin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/bin/vendor_perl:/usr/bin/core_perl"
  PATH="${PATH:+$mypath}"
  export PATH
fi                     
