#!/usr/bin/env zsh
eval $(ssh-agent -s)
ssh-add
gpg-agent --daemon --enable-ssh-support \
  --write-env-file "${HOME}"/.gpg-agent-info
eval $(dircolors -b ~/.config/dircolors/dircolors)
mpd
stty -ixon

if [[ -o interactive ]]; then
fi                     
