#!/usr/bin/env zsh
skip_global_compinit=1
mypath="$HOME/bin:$HOME/.cabal/bin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/bin/vendor_perl:/usr/bin/core_perl"
export PATH="$mypath"
export PATH
export GREP_OPTIONS='--color=auto'
export DISPLAY="${DISPLAY:-:0}"
export EDITOR=vim
export VISUAL=vim
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
export LESS="-R"
export ABSROOT="$HOME/builds/abs"
export HELPDIR="$HOME/.config/zsh/help"
export TERMINAL="termite"
export PYTHONDOCS=/usr/share/doc/python/html/
export BROWSER="firefox"
unset TMUX 
