#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

numlockx &
setxkbmap -option caps:super
setxkbmap -option compose:menu
xrdb -load ~/.Xresources
compton -D 6 -i 0.6 -e 0.6 -cCfFGb
~/bin/wallpaper &
termite tmux a -t shell &
xbindkeys
redshift -l 45.5:122.7 -m randr &

exec i3 #-d all -V &>i3.dump

# vim: ft=sh
