#
# ~/.bashrc
#

[[ $- == *i* ]] || return
exec 9>&2 2>/dev/null

shopt -s extglob dotglob

# rubies=( "$HOME"/builds/rubies/* )

alias ls='ls --color=auto --group-directories-first -Fh'
alias e='emacsclient -t'
alias ec='emacsclient -c'
PS1='[\u@\h \W]\$ '
PS4='+ ${FUNCNAME[0]}:$LINENO:'

exec 2>&9 9>&-
