#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '
PS4='+ ${FUNCNAME[0]}:$LINENO:'
alias paste='curl -F "sprunge=<-" http://sprunge.us'
